### ISSUE TITLE
OAuthSimple Error

### ISSUE THREAD

**Issue by denzelwamburu** [aksalj/pesapaljs#10]
Thank you for the great Library, though am running into errors while trying to install packages in the web example. 
Still running into error after installing the OAuthSimple module.

`Error: Cannot find module 'OAuthSimple'
    at Function.Module._resolveFilename (module.js:337:15)
`.

**Comment by denzelwamburu** [comment]
@aksalj  i found the error, seems the oauthsimple doesn't index the main js file primarily since it has packages for other languages, fixing the the require from `var OAuthSimple = require(oauthsimple.');` to `var OAuthSimple = require('../../node_modules/oauthsimple/OAuthSimple.js');` seems to work :smiley: . Will create a PR.

**Comment by aksalj** [comment]
@denzelwamburu `...js/js/OAuthSimple.js` is listed as `oauthsimple`'s [entry point](https://github.com/idottv/oauthsimple/blob/master/package.json#L5). So that error should not occur; in fact I am unable to reproduce it...

**Comment by aksalj** [comment]
This error occurs if you try to run the example without installing the library's dependency - because the example does not list `pesapaljs` as its dependency as one would normally do... So to run the example one should `npm install` in both `/` and `/example/web`
