### ISSUE TITLE
Request takes long

### ISSUE THREAD

**Issue by splatigo** [aksalj/pesapaljs#14]
The module works fine, however, it takes long to connect to pesapal and am doing a development test at heroku.com, however it usually times out before API response, what could be best solution.

**Comment by aksalj** [comment]
Is it possible to share any logs?

**Comment by splatigo** [comment]
{ request:
   { uri: 'https://demo.pesapal.com/api/postpesapaldirectorderv4/postpayment',
     method: 'POST',
     headers:
      { 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2049.0 Safari/537.36',
        Referer: 'https://demo.pesapal.com/api/postpesapaldirectorderv4?oauth_callback=http%3A%2F%2Fdummysite.se%3A8528%2Fcallback%2F&oauth_consumer_key=CsyPrmwhWtGBbFEN7ATNPTVE0N%2
a8oFk&oauth_signature=Gjvfiu083KdBguPSbpzisRSSp44%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1474540772&pesapal_request_data=%26lt%3B%3Fxml%20version%3D%26quot%3B1.0%26quot
6quot%3Butf-8%26quot%3B%3F%26gt%3B%26lt%3BPesapalDirectOrderInfo%20xmlns%3Axsi%3D%26quot%3Bhttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema-instance%26quot%3B%20xmlns%3Axsd%3D%26quot%3Bht
rg%2F2001%2FXMLSchema%26quot%3B%20Amount%3D%26quot%3B10000%26quot%3B%20Currency%3D%26quot%3BUGX%26quot%3B%20Description%3D%26quot%3BTicket%20Payment%26quot%3B%20Type%3D%26quot%3BMER
eference%3D%26quot%3B1474539773685%26quot%3B%20FirstName%3D%26quot%3BPeter%26quot%3B%20LastName%3D%26quot%3BLatigo%26quot%3B%20Email%3D%26quot%3Bpeterlatigo%40yahoo.com%26quot%3B%20
ot%3B%26quot%3B%20xmlns%3D%26quot%3Bhttp%3A%2F%2Fwww.pesapal.com%26quot%3B%20%2F%26gt%3B',
        host: 'demo.pesapal.com',
        cookie: 'ASP.NET_SessionId=azgd41fxjocsunqm22qtoo5f',
        'content-type': 'application/x-www-form-urlencoded' },
     body: 'PaymentData=2CF80623577311BA400F5061796D656E7456696577446174613F024964823F045479706598365065736170616C2E5061796D656E744170692E5765622E4D6F64656C732E56696577446174612E506
//other body parts go here
     ....
     //the ending parts of the body
     4669656C643F024964887C99084D
	5F6B5F5F4261636B696E67466965
	TransactionCode=5904' } }

/*Part of the response from Pesapal */

lass="payment-option-form">\r\n\t\r\n</div>\r\n        <div class="control-group">\r\n
   <div class="controls">\r\n\t\t\t\t<input id="Username" name="Username" type="text" value=""
>*</span>\r\n\t\t\t</div>\r\n        </div>\r\n        <div class="control-group">\r\n
class="controls">\r\n\t\t\t\t<input id="Password" name="Password" type="password" />\r\n\t\t\t\
\t\t\t</div>\r\n        </div>\r\n    </div>\r\n</fieldset>\r\n\r\n            </div>\r\n
 type="submit" name="submitButton" value="Complete" class="btn btn-primary btn-medium apisubmit
ss="span5 row-fluid">\r\n\t\r\n<p class="demo-msg">\r\n    <b>*Please NOTE that this is a TEST
r mobile phone! You may <a href="/MobileMoneyTest/Index" target="_blank">click here</a>\r\n
>\r\n    <div id="image">\r\n        <a href="https://demo.pesapal.com/Home/Index" target="_bla
div>\r\n    <p>\r\n        100% secure payments processed by <a href="/home/index" target="_bla
get="_blank">Verisign SSL</a>. In order to protect your card from unauthorised use, PesaPal may

That's what usually happens between, however, whole of that process takes about between 30 -50 seconds to complete. Most servers deny the request.

![fl](https://cloud.githubusercontent.com/assets/10112548/18745850/a4447954-80cc-11e6-8fee-67878a9a4f5c.PNG)

**Comment by aksalj** [comment]
Can't seem to reproduce those times...😕  Longest I get is around 3 seconds, calling from the slowest network I could find! Could it be something about your setup?

**Comment by splatigo** [comment]
What possible setup configs could be the issue. Let me possibly try so I can achieve about that 3s.

**Comment by splatigo** [comment]
Sure, it takes 3s with good internet, some configs were wrong, the module didn't include the payment methods for UG. Had added it in the core, but not made the changes in the scraper.js file from lib. Should contribute the changes.
