### ISSUE TITLE
How to use the "Mobile Payment" option in the web example in PesaPal demo

### ISSUE THREAD

**Issue by ManguruMuiruri** [aksalj/pesapaljs#15]
Hi,

Thank you for this great library. Am trying out the "Mobile Payment" option but am not able to pay successfully.
Am using the Confirmation code returned by this mobile test money https://demo.pesapal.com/mobilemoneytest as the Transaction code to complete the "Pay" process but am getting a TypeError 
![image](https://cloud.githubusercontent.com/assets/8164311/19018003/7fcbcaaa-881f-11e6-8c13-41b69878931d.png)

My demo accounts both Buyer and Merchant are setup correctly and "Payment on PesaPal" works fine.
Is there something that i am missing for the "Mobile Payment" option?

**Comment by splatigo** [comment]
I think you are using an old module, install the latest and probably it could fix the problem. The issue probably is to do with changes in pesapal API itself. So the module too was changed. pesapal used to connect to http://.demo.pesapal.com, now it is to https.

**Comment by ManguruMuiruri** [comment]
Thank you splatigo. That solved the problem.
