### ISSUE TITLE
How to use the IPN while developing (locally)

### ISSUE THREAD

**Issue by Alfred-W** [aksalj/pesapaljs#16]
This is an amazing package you have here...
I have tried to use the IPN for pesapal while developing and I can't seem to get it right. I have set the url to localhost:30000/ipn but then my qs is, 'What next?' How is the IPN supposed to work. Sadly the documentation does not address this well.

**Comment by aksalj** [comment]
Hey @Alfred-W 

Because your IPN endpoint **needs to be accessible from the Internet**(i.e. visible to PesaPal's servers), working with localhost is a bit tricky. I use tools like [localtunnel](https://localtunnel.github.io/www/) to test IPN on localhost.

1. Run your app locally, say on port `3000`
2. Run `localtunnel` with a custom subdomain, say `alfred`
```shell
$ lt -s alfred -p 3000
```
3. Register `https://alfred.localtunnel.me` in your dev portal on PesaPal
4. Enjoy!

In my setup 👇 👇 , the `GET /ipn?pesapal_notification_type=CHANGE...` request was made by PesaPal's server.

![screen shot 2016-12-23 at 10 12 35 am](https://cloud.githubusercontent.com/assets/2534772/21448977/58c7a008-c8f9-11e6-89e6-e8ddf5e7646e.png)

**Comment by Alfred-W** [comment]
@aksalj Thanks alot

**Comment by Alfred-W** [comment]
I still have difficulties getting the IPN to work...I need your help on this. My questions are as follows:
1. The IPN is supposed to be called automatically by Pesapal as long as the correct URL is entered in the dashboard right?
2. The URL called can do anything from trigger an e-mail to console to a log. Its just a URL right?
3. My workflow is as follows : Go to a URL, the payment is made to Pesapal successfully and the transaction is succesfully recorded in the dashboard, but thats it. Even though I have the IPN route setup in my code, nothing happens after the payment goes through. 

Thanks again for this library

**Comment by aksalj** [comment]
@Alfred-W if you have **registered your IPN URL on the dev portal on PesaPal** and you still can't get notifications, it's probably because it (the URL) **cannot be reached** by PesaPal.

**Comment by Alfred-W** [comment]
@aksalj I used localtunnel to make my local env accessible online and tested the IPN, still with no luck. I intend to put the demo I have on Digital Ocean and see whether it will work. 

**Correct me if I'm wrong** but an IPN is supposed to be called automatically (in this case by Pesapal) when the payment status of a transaction changes. For example, I can register the URL to send emails to clients after successful payment and this will be called by Pesapal when the payment is indeed successful.

**Comment by aksalj** [comment]
>**Correct me if I'm wrong** but an IPN is supposed to be called automatically (in this case by Pesapal) when the payment status of a transaction changes. For example, I can register the URL to send emails to clients after successful payment and this will be called by Pesapal when the payment is indeed successful. 

☝️ That is correct.

My setup, as shown [above](#issuecomment-268950658), is working OK, as you can see, I'm `console.log()` the request as recieved from PesaPal.

**Comment by Alfred-W** [comment]
Okay thanks. Let me put it up, set up the IPN see what happens. I should have made some strides by the end of the day

**Comment by Alfred-W** [comment]
@aksalj Thanks alot for the support. This works well. Windows kept blocking the incoming requests but using Heroku works like a charm. I might fork this repo and create a different web project.
