### ISSUE TITLE
Error calling getPaymentDetails and getPaymentStatus

### ISSUE THREAD

**Issue by alexmasita** [aksalj/pesapaljs#4]
Hi Aksalj,

Thank you for making this module available to the rest of us.  I was directed to you by one of the pesapal developers to see if you can help me with this issue.  Here below is the email I sent them with the details of my demo account and the background of my problem.  Looking forward to hearing your views.

API Credentials
Consumer Key: T5x+24rSIGTlP0PhWZmJpa+iXXNbVt7j

Consumer Secret: ouQeMigjjK3yhFXhOHtmHHLT9b0=

Merchant Email: masita@zuru360.com

```
31-Aug-2015 null nullmasita@zuru360.comM-PesaKE90KR803 Completed Ksh. 100.00 55e42492456307c784582730
31-Aug-2015 null nullmasita@zuru360.comM-PesaUH51BC828 Completed Ksh. 100.00 55e41c3da98821d06d9e0b30
31-Aug-2015 null nullmasita@zuru360.comM-PesaTN31PA857 Completed Ksh. 100.00 55e41a7f78ce2ca5664e3e12
30-Aug-2015 null nullmasita@zuru360.comM-PesaEH21RV452 Completed Ksh. 100.00 55e36f5c8cf175a43fcba987
30-Aug-2015 null nullmasita@zuru360.comM-PesaLW11NN444 Completed Ksh. 100.00 55e35beb2babcdd82469954b
```

As discussed, I believe I am using the right consumer key and secret from the `demo.pesapal.com` because I was able to successfully call `PesaPal.getPaymentURL` and retrieve a valid pesapal iframe url.  However, I cannot understand why calling `PesaPal.paymentDetails` on the same object fails with the below error.  Perhaps you can enlighten me.
here is the error I see on the mark terminal from the node server:

```javascript
{ 
request: 
   { uri: 'http://demo.pesapal.com/api/querypaymentdetails?pesapal_merchant_reference=55e44bf8d6b10723fa2e7488&pesapal_transaction_tracking_id=0164bcc1-ac7b-49d6-92a7-2fc88640303a',
     method: 'GET',
     headers: 
      { host: 'demo.pesapal.com',
        Authorization: 'OAuth oauth_consumer_key="T5x%2B24rSIGTlP0PhWZmJpa%2BiXXNbVt7j",oauth_nonce="a145a928ed784f6dbc1055d513c7b386",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1441032332",oauth_version="1.0",oauth_signature="VtL0ULvVyFMz7%2Bwlu3Dc4B0sA0U%3D"' } } }
{ response: 
   { headers: 
      { 'cache-control': 'private',
        server: 'Microsoft-IIS/8.5',
        'set-cookie': [Object],
        'x-aspnetmvc-version': '5.0',
        'www-authenticate': 'OAuth realm="", oauth_problem="consumer_key_unknown"',
        'proxy-support': 'Session-Based-Authentication',
        'x-aspnet-version': '4.0.30319',
        'x-powered-by': 'ASP.NET',
        date: 'Mon, 31 Aug 2015 14:45:33 GMT',
        connection: 'close',
        'content-type': 'text/html;charset=utf-8',
        'content-length': '45' },
     statusCode: 200,
     body: 'Problem: consumer_key_unknown | Advice: >  | ' } 
}
```

NB: I notice in the error message, the oauth_consumer_key special characters appear to be encoded!  Is this expected?  My assumption is they are decoded by pesapal on their end so it should not be the issue.  Let me know.

**Comment by aksalj** [comment]
Hey!

At first glance, it looks like `pesapal`'s oauth implementation is not accepting encoded special characters in the consumer key (At least for this endpoint, an maybe the one raised in issue #3 ).

However, the OAuth 1.0 specs ([RFC 5849](https://tools.ietf.org/html/rfc5849)) clearly [say](https://tools.ietf.org/html/rfc5849#page-27) that the `Authorization` Header parameter names and values are encoded using [Percent Encoding](https://tools.ietf.org/html/rfc5849#section-3.6). So I think your assumption is correct.

I need to investigate this issue further to find out if the problem is with how the library is interacting with the API or if the API itself is not behaving as expected.

**Comment by aksalj** [comment]
**UPDATE**: After a quick test, it appears that consumer keys that have no special characters are working just fine. This kinda proves that the problem is with the API's inconsistent oauth implementation. But still, need to run more tests, reviews and talk to pesapal just to be sure... :construction: 

If you find any solutions before then, PRs are welcome! :wink:

**Comment by alexmasita** [comment]
This is great.  Many thanks for your immediate response.  I eagerly await your findings ..... will take a look at the source to see if I can be of any help on this.........

**Comment by alexmasita** [comment]
Hi Aksalj, were you able to verify with pesapal about this issue?

**Comment by aksalj** [comment]
No, still waiting for Pesapal's response...

**Comment by alexmasita** [comment]
Hi Mark,

Hope you are well.

I believe Aksalj had submitted a query to Pesapal regarding this issue
https://github.com/aksalj/pesapaljs/issues/4.  Could you follow up on it
please.

Many thanks,

 *Alex Masita*
Research and Development Director

t: 254713590577 | e: masita@zuru360.com |
w: www.zuru360.com

**Comment by alexmasita** [comment]
I have not seen the issue, is it on the Forum or email?


Mark Mwongela
Managing Director
Verviant Consulting Services
Web, Software and Mobile Development
http://www.verviant.com <http://www.verviant.com/>, http://www.verviant.com/portfolio <http://www.verviant.com/portfolio>
 
Telephone : +254 (0)20 2124722 | +254 735444635

**Comment by alexmasita** [comment]
Hi Mark,

I believe the issue is captured on this github link:
https://github.com/aksalj/pesapaljs/issues/4, however let us allow Aksalj
to respond to you whether it has been sufficiently captured on the link I
have just provided or re-submit to you directly his query.

Many thanks,

 *Alex Masita*
Research and Development Director

t: 254713590577 | e: masita@zuru360.com |
w: www.zuru360.com

**Comment by evanomondi** [comment]
Hi. We are about to start using this. Have you figured out a solution?

**Comment by alexmasita** [comment]
Hi Evan,

Yes, not completely.

I was able to get to display the 'pesapal payment options' iframe page but
if fails calling the "getPaymentDetails" api.

Still waiting for feedback from our good friends at Pesapal on issues
raised by Aksalj.

Let us see how this week goes.


 *Alex Masita*
Research and Development Director

t: 254713590577 | e: masita@zuru360.com |
w: www.zuru360.com

**Comment by alexmasita** [comment]
Thanks Alex. Also hoping for a reply from them

On 27 September 2015 at 19:33, Alex Masita <masita@zuru360.com> wrote:

> Hi Evan,
>
> Yes, not completely.
>
> I was able to get to display the 'pesapal payment options' iframe page but
> if fails calling the "getPaymentDetails" api.
>
> Still waiting for feedback from our good friends at Pesapal on issues
> raised by Aksalj.
>
> Let us see how this week goes.
>
>
>  *Alex Masita*
> Research and Development Director
>
> t: 254713590577 | e: masita@zuru360.com |
> w:
> <https://contactmonkey.com/api/v1/tracker?cm_session=1dc71240-b908-47b4-86c3-01137d3dc00f&cm_type=link&cm_link=5309afa5-d18d-4afd-bcd4-87f1a2218049&cm_destination=http://www.zuru360.com/>
> www.zuru360.com
> <https://contactmonkey.com/api/v1/tracker?cm_session=1dc71240-b908-47b4-86c3-01137d3dc00f&cm_type=link&cm_link=5d476b5a-0cc0-4168-9599-e30d202f331b&cm_destination=http://www.zuru360.com>
>
> On Sun, Sep 27, 2015 at 3:14 PM, evan omondi <evanomondi7@gmail.com>
> wrote:
>
>> Hi Alex,
>>
>> Were you able to use this
>> <https://contactmonkey.com/api/v1/tracker?cm_session=b955a1c4-3c4c-4e97-b636-d2d747393583&cm_type=link&cm_link=ce6d9fdd-0176-41c0-882b-f53c5c1961dc&cm_destination=https://github.com/aksalj/pesapaljs>pesapal
>> module on a project successfully?
>>
>> Regards
>>
>> Evan
>>
>
>


-- 

About Me |
<https://contactmonkey.com/api/v1/tracker?cm_session=1dc71240-b908-47b4-86c3-01137d3dc00f&cm_type=link&cm_link=10400096-b704-4c7f-a3e0-4c1c61bb9f28&cm_destination=http://www.evantech.co/#!/about">
My
Portfolio  |
<https://contactmonkey.com/api/v1/tracker?cm_session=1dc71240-b908-47b4-86c3-01137d3dc00f&cm_type=link&cm_link=2049fb7c-5204-466b-a79c-67f9c6a3aaf6&cm_destination=http://www.evantech.co/#!/portfolio">
 Contact Me
<https://contactmonkey.com/api/v1/tracker?cm_session=1dc71240-b908-47b4-86c3-01137d3dc00f&cm_type=link&cm_link=f29301aa-2e03-4d0d-bcd8-ad48367b76f2&cm_destination=http://www.evantech.co/#!/contacts">
[image: Like our Electronics fun page]
<https://contactmonkey.com/api/v1/tracker?cm_session=1dc71240-b908-47b4-86c3-01137d3dc00f&cm_type=link&cm_link=1839378a-d720-43b3-b8be-b29661349585&cm_destination=https://www.facebook.com/EvanTechn>
[image:
Follow us on twitter]
<https://contactmonkey.com/api/v1/tracker?cm_session=1dc71240-b908-47b4-86c3-01137d3dc00f&cm_type=link&cm_link=393fb2e9-86a6-4422-8ed2-67a8987443f0&cm_destination=https://twitter.com/EvanTechnology>
[image:
Add Jumia on Google+]
<https://contactmonkey.com/api/v1/tracker?cm_session=1dc71240-b908-47b4-86c3-01137d3dc00f&cm_type=link&cm_link=25467c76-9b61-44a9-9970-6478f38c82a5&cm_destination=https://plus.google.com/b/101642258208450678535/101642258208450678535/about?hl=en>

**Comment by clarkritchie** [comment]
Also interested in their response on this.

**Comment by aksalj** [comment]
Still waiting for Pesapal's response to my email :disappointed:  But I also created a [topic](http://developer.pesapal.com/forum/2-pesapal-integration/1609-encoded-comsumer-key-being-rejected) of their forum. Maybe you guys should do the same so we can find a solution to this issue quickly :wink:

**Comment by clarkritchie** [comment]
@aksalj I emailed them yesterday and they responded with.  Ugh, they don't seem to understand the issue.

Pesapal currently does not accept the Key and/or secret when it has been encoded so when passing the key and secret, kindly ensure that these are not encoded and are as exact as shared on Email for live or Dashboard for the Sandbox

Regards

Mark Mwongela
Managing Director
Verviant Consulting Services

**Comment by clarkritchie** [comment]
Um, is this just me?  `getPaymentURL` returns the encoded key in the URL so the redirect doesn't work.

![image](https://cloud.githubusercontent.com/assets/385550/10345103/12602344-6cdc-11e5-81dd-57b21236d4b7.png)

**Comment by lycin** [comment]
@alexmasita 
I've checked how your consumer key is translated when you urlencode. The way the + is being translated will not work on Pesapal. So either, ensure it stays + or is translated to %20
A workaround in java is as follows, I hope it gives you an idea
 return URLEncoder.encode(s, ENCODING)
                    .replace("+", "%20").replace("*", "%2A")
                    .replace("%7E", "~");

**Comment by lycin** [comment]
@clarkritchie , an demo account will not work on pesapal live (going by your screenshot above)

**Comment by clarkritchie** [comment]
@lycin But that's the URL that's given back to me from `getPaymentURL`?  Do I need to manually replace `www.` with `demo.` during development?  Thanks.

**Comment by lycin** [comment]
@clarkritchie,If that is the redirect URL, then that is fine. However, just counter check to ensure that you are sending the request to demo.pesapal.com. That can also result in the error above. Otherwise, try encoding the URL as I have explained above and test

**Comment by clarkritchie** [comment]
`.replace("+", "%20")` --`%20` not `%2B`?  No luck yet.

```
        _header: 'GET /api/querypaymentdetails?pesapal_merchant_reference=1444309235095&pesapal_transaction_tracking_id=54e2b722-a73f-4070-9031-696ba4cffd7b HTTP/1.1\r\nhost: demo.pesapal.com\r\nAuthorization: OAuth oauth_consumer_key="7LDnDfgy2K61oX1jR2ux0%2BxZNmFxNa6d",oauth_nonce="1491de0f441f4da2bb64f9a25692b4fc",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1444309252",oauth_version="1.0",oauth_signature="%2FzT4%2FpUJAEHdnH%2Fur5Q75sZGVco%3D"\r\nConnection: close\r\n\r\n',
```

**Comment by aksalj** [comment]
A pesapal dev [insists](http://developer.pesapal.com/forum/2-pesapal-integration/1609-encoded-comsumer-key-being-rejected#1612) we are mixing up the keys or using some invalid ones somehow :anguished: 

Regardless, why is pesapal's OAuth implementation inconsistent? Why does it appear to accept a consumer key on one endpoint(`demo.pesapal.com/api/PostPesapalDirectOrderV4`) and refuse it on another (`demo.pesapal.com/api/QueryPaymentDetails`)?

@lycin 
Like @clarkritchie says, it does not seem to make a difference if you encode `+` as `%2B` or `%20`; if the consumer key has some encoded characters, it is still being rejected. Plus, we can't just hack away a few characters on some keys, we are/should be following the standard ([RFC 5849](https://tools.ietf.org/html/rfc5849#page-27)).

**Comment by clarkritchie** [comment]
Thanks for the confirmation, @aksalj.  You are spot-on.  I tracked this to the lowest level on the JS side, the error is on PesaPal's side -- the implementation is inconsistent and broken on this one call.

**Comment by aksalj** [comment]
**Update**: After running some more tests, I have found this problem is not restricted to the demo endpoints. Even the live API is affected :-1:  and it is only the `consumer_key` that is not being decoded properly.

**Comment by clarkritchie** [comment]
Thanks for the update.  We've been emailing this to Mark Mwongela, Technical Director, but nothing yet in terms of a solution.

**Comment by clarkritchie** [comment]
Well, we moved on.  The Kopo Kopo API is working swimmingly. :+1:

**Comment by evanomondi** [comment]
Hi @clarkritchie where can I find this api, and does it work with nodejs?

**Comment by aksalj** [comment]
Hey Evan!
It's [here](http://www.kopokopo.co.ke/) and [https://app.kopokopo.com/push_api](https://app.kopokopo.com/push_api).

**Comment by evanomondi** [comment]
Thanks @aksalj

**Comment by clarkritchie** [comment]
@evanomondi Sure does.  Actually their approach is very simple and clean.  Love it.

**Comment by aksalj** [comment]
@alexmasita @clarkritchie @evanomondi What do you think if we solved this issue like #9. The issue (improper parsing of the `Authorization` header field) will still remain on Pesapal but at least we can fetch payment details when our consumer keys have `+`s and other special characters.

**Comment by alexmasita** [comment]
Hi Aksal,

Once again thank you for your efforts to resolve the issues in this regard.

Interestingly, at the Pesapal offices, we noticed a discrepancy along the
lines of the solution you are offering.

It appeared like you were signing the url in the "PesaPal.getPaymentURL"
call but not on the other calls that were failing.  So I was going to
propose that we try and implement the same signing procedure on all the
failing calls to see if the issue could be resolved.

Specifically, in the "PesaPal.getPaymentURL" call, you were using the
following method "var req = signer.sign(signParams);" for signing which
were actually missing in the other calls.

Have you verified that your refactor resolves the issues on the failing
calls?

Will retry your library in the course of the afternoon also to verify.

With warm regards,

 *Alex Masita*
Research and Development Director

t: 254713590577 | e: masita@zuru360.com |
w: www.zuru360.com

**Comment by clarkritchie** [comment]
Hey @aksalj, I don't have much of an opinion as we took our business to Kopo Kopo.

**Comment by venueskenya** [comment]
I found out what  causes that probelm. when in production mode, one needs to uncheck - **Use Demo Gateway** . It will work like charm. see [http://simplysandara.com](url). you can [hire us](http://www.nichewebcreation.co.ke/)
