### ISSUE TITLE
How to simulate mPesa payment for testing?

### ISSUE THREAD

**Issue by clarkritchie** [aksalj/pesapaljs#7]
Hey thanks for making this library!

Any suggestions on how to simulate an mPesa payment from outside Kenya?  I assume there's a way I can initiate fake transactions against their demo.pesapal.com environment so that I can simulate a successful or failed payment transaction to my Node app.

Or, maybe an IPN simulator is what I need.  Looks like PayPal has [such a thing](https://developer.paypal.com/developer/ipnSimulator/)...

Thanks in advance for any recommendations!

**Comment by aksalj** [comment]
Hey :wink:!

You can use [http://demo.pesapal.com/MobileMoneyTest/Index](http://demo.pesapal.com/MobileMoneyTest/Index) to test mobile money transfer to PesaPal.

**Comment by clarkritchie** [comment]
Awesome, thanks!!!  Their developer documentation leaves much to be desired...

**Comment by aksalj** [comment]
Yeah, it's terrible!

**Comment by clarkritchie** [comment]
I'll put in a PR with a modified README for you as I uncover these semi and un-documented tricks for n00bs. :-)
